### ISSUE TITLE
 Error: OAI-PMH provider returned an error: ListRecords verb must receive the metadataPrefix parameter

### ISSUE THREAD

**Issue by jmaferreira** [paperhive/oai-pmh#12]
```
(node:17832) UnhandledPromiseRejectionWarning: Error: OAI-PMH provider returned an error: ListRecords verb must receive the metadataPrefix parameter
    at new OaiPmhError (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/oai-pmh/dist/utils.js:40:11)
    at _parseOaiPmhXml (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/oai-pmh/dist/utils.js:66:11)
    at _parseOaiPmhXml.next (<anonymous>)
    at onFulfilled (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/co/index.js:65:19)
    at tryCatcher (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
(node:17832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:17832) UnhandledPromiseRejectionWarning: Error: OAI-PMH provider returned an error: ListRecords verb must receive the metadataPrefix parameter
    at new OaiPmhError (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/oai-pmh/dist/utils.js:40:11)
    at _parseOaiPmhXml (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/oai-pmh/dist/utils.js:66:11)
    at _parseOaiPmhXml.next (<anonymous>)
    at onFulfilled (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/co/index.js:65:19)
    at tryCatcher (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/mferreira/git/ipca-pw/oai-pmh-harvester/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
(node:17832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

When trying to harvest "http://arca.igc.gulbenkian.pt/oaiextended/request"

**Comment by jmaferreira** [comment]
The test to see if we have reached the last resumptionToken can be improved as follows:

 ```
   // is this the last element?
      if (self.currentIndex >= list.length) {
        // do we have a resumption token?
        if (token && token._) {
          let cursor = get(token, '$.cursor');
          let completeListSize = get(token, '$.completeListSize');
          if (cursor !== undefined && completeListSize !== undefined) {
            cursor = parseInt(cursor, 10);
            completeListSize = parseInt(completeListSize, 10);
            if (cursor + list.length >= completeListSize) {
              // we got 'em all
              self.done();
            }
          }
        } else {
          // no resumption token
          self.done();
        }
```

This fixes the issue. The key line is:
```
   if (token && token._) {
```

**Comment by andrenarchy** [comment]
I'm not sure how the error message you get is related to the resumptionToken. It seems like it's due to a missing metadataPrefix parameter. Please reopen if providing the parameter (`-p` for the CLI) doesn't fix it.

**Comment by jmaferreira** [comment]
Hi,

I'm not using the CLI. I'm using the library. This error occurs with multiple repositories. You can replicate the issue by harvesting: http://arca.igc.gulbenkian.pt/oaiextended/request

**Comment by andrenarchy** [comment]
I still think the missing `metadataPrefix` is the reason. Can you try with the new example in the README?
