### ISSUE TITLE
Error runinng sample code.

### ISSUE THREAD

**Issue by scoobie** [paperhive/oai-pmh#20]
I am getting the following error running the sample code.
My Node version is v10.5.0 and npm 6.1.0

(function (exports, require, module, __filename, __dirname) { import { OaiPmh } from 'oai-pmh'
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)

**Comment by andrenarchy** [comment]
Seems like you're not running it with `node -r esm`? I'm closing this but if this doesn't solve the problem just reopen.
