### ISSUE TITLE
GetRecord async error

### ISSUE THREAD

**Issue by matteoLorenzini** [paperhive/oai-pmh#21]
From this script

import { OaiPmh } from 'oai-pmh'

async function main () {
  const oaiPmh = new OaiPmh('http://www.culturaitalia.it/oaiProviderCI/OAIHandler')
  const identifierIterator = oaiPmh.getRecord({
    metadataPrefix: 'oai_dc',
    identifier:'oai:culturaitalia.it:oai:www.michael-culture.it:pub-it/dcollection/IT-DC-e555496e'
  })
  for await (const identifier of identifierIterator) {
    console.log(identifier)
  }
}

main().catch(console.error)

Running the command getRecord I got this error(s)

TypeError: identifierIterator is not async iterable
    at main (/Users/matteo/vsProject/OAI-PMH/richiesta_terminale.js:9:34)
    at Object.<anonymous> (/Users/matteo/vsProject/OAI-PMH/richiesta_terminale.js:14:1)
    at Cl (/Users/matteo/node_modules/esm/esm.js:1:210825)
    at Object.run (/Users/matteo/node_modules/esm/esm.js:1:209532)
    at Object.<anonymous> (/Users/matteo/vsProject/OAI-PMH/richiesta_terminale.js:1:86)
    at Object.<anonymous> (/Users/matteo/node_modules/esm/esm.js:1:223819)
    at eu (/Users/matteo/node_modules/esm/esm.js:1:217938)
    at /Users/matteo/node_modules/esm/esm.js:1:219136
    at ou (/Users/matteo/node_modules/esm/esm.js:1:219372)
    at Object.g (/Users/matteo/node_modules/esm/esm.js:1:230080)
(node:23762) UnhandledPromiseRejectionWarning: OaiPmhError: OAI-PMH provider returned an error: The request includes illegal arguments, is missing required arguments, includes a repeated argument, or values for arguments have an illegal syntax.
    at new OaiPmhError (/Users/matteo/node_modules/oai-pmh/src/errors.js:8:11)
    at parseOaiPmhXml (/Users/matteo/node_modules/oai-pmh/src/oai-pmh-xml.js:24:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23762) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23762) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by andrenarchy** [comment]
`getRecord` only returns one element so it's not an iterator. You can do the following:
```javascript
import { OaiPmh } from 'oai-pmh'

async function main () {
  const oaiPmh = new OaiPmh('http://www.culturaitalia.it/oaiProviderCI/OAIHandler')
  const record = await oaiPmh.getRecord('oai:culturaitalia.it:oai:www.michael-culture.it:pub-it/dcollection/IT-DC-e555496e', 'oai_dc')
  console.log(record)
}

main().catch(console.error)
```
